[package]
name = "tls_checker"
version = "0.1.0"
edition = "2021"
authors = ["Jade"]
license = "GPL-3.0-only"

[dependencies]
clap = {version = "3.0", features = ["derive"]}
futures = "0.3"
reqwest = "0.11"
tokio = { version = "1.15", features=["full"] }
